import Header from "@/components/Header";
import Footer from "@/components/Footer";

import localFont from "next/font/local";
import "./globals.css";
import { Box } from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Box sx={{display:'flex', flexDirection:'column'}}>       
          <Header/>
          <Box flexGrow={1}>
            {children}
          </Box>
          <Footer/>
        </Box>        
      </body>
    </html>
  );
}
